name: kulon
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  flutter_easyloading: ^3.0.5 
  easy_debounce: ^2.0.2+1
  google_fonts: ^5.1.0 
  image_picker: ^1.0.4
  equatable: ^2.0.5 
  dartz: ^0.10.1
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true